import Head from 'next/head';
import { useState } from 'react';
//hooks
import { useLocalStorage } from './hooks/useLocalStorage';
//components
import { FormContact } from './components/FormContact';
import { FormGroup } from './components/FormGroup';
import { Contact } from './components/Contact';
import { Group } from './components/Groups';
//css
import styles from '../styles/Home.module.css';

export default function Home() {
  const [addContact, setAddContact] = useState(false);
  const [addGroup, setAddGroup] = useState(false);
  const [search, setSearch] = useState('');
  const [dragData, setDragData] = useState({});
  //storage
  const [contact, setContact] = useLocalStorage([], 'contacts');
  const [group, setGroup] = useLocalStorage(['contacts'], 'groups');
  //functions toogle
  function handlerFormContact(e) {
    e.preventDefault();
    setAddContact(!addContact);
  }
  function handlerFormGroup(e) {
    e.preventDefault();
    setAddGroup(!addGroup);
  }
  //function search filtered by name

  const filteredContact = contact.filter((person) => {
    return person.name.toLowerCase().includes(search.toLowerCase());
  });

  //function drag and drop

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div>
        <section>
          <h1>Grupos</h1>
          <ul>
            <li style={{ border: 'solid 2px green' }}>
              <h1>Contactos</h1>
              <input
                type='search'
                name='searchContact'
                id='searchContact'
                onChange={(e) => setSearch(e.target.value)}
              />

              <div>
                <ul>
                  {search.length > 0 &&
                    filteredContact.map((data, index) => {
                      return (
                        <Contact
                          key={index}
                          data={data}
                          id={index}
                          setDragData={setDragData}
                        />
                      );
                    })}
                </ul>
                <ul>
                  {contact.length > 0 &&
                    search.length < 1 &&
                    contact.map((data, index) => {
                      return (
                        <Contact
                          key={index}
                          data={data}
                          id={index}
                          setDragData={setDragData}
                        />
                      );
                    })}
                </ul>
              </div>
            </li>
            {group.length > 0 &&
              group.slice(1).map((value, index) => {
                return (
                  <Group
                    key={index}
                    data={value}
                    contact={contact}
                    setDragData={setDragData}
                    setContact={setContact}
                    dragData={dragData}
                  />
                );
              })}
          </ul>
        </section>
      </div>
      <section>
        crear grupo y contacto
        <button onClick={handlerFormContact}>Añadir Contacto</button>
        {addContact && (
          <FormContact
            setAddContact={setAddContact}
            setContact={setContact}
            contact={contact}
          />
        )}
        <button onClick={handlerFormGroup}>Crear Grupo</button>
        {addGroup && (
          <FormGroup
            group={group}
            setGroup={setGroup}
            setAddGroup={setAddGroup}
          />
        )}
      </section>
    </div>
  );
}
