import Head from 'next/head';
import { useState } from 'react';
//hooks
import { useLocalStorage } from './hooks/useLocalStorage';
//components
import { FormContact } from './components/FormContact';
import { FormGroup } from './components/FormGroup';
import { Contact } from './components/Contact';
//css
import styles from '../styles/Home.module.css';
import { Group } from './components/Groups';

export default function Home() {
  const [addContact, setAddContact] = useState(false);
  const [addGroup, setAddGroup] = useState(false);
  //storage
  const [contact, setContact] = useLocalStorage([], 'contacts');
  const [group, setGroup] = useLocalStorage([], 'groups');

  function handlerFormContact(e) {
    e.preventDefault();
    setAddContact(!addContact);
  }
  function handlerFormGroup(e) {
    e.preventDefault();
    setAddGroup(!addGroup);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <section>
        <ul>
          {group.length > 0 &&
            group.map((value, index) => {
              return <Group key={index} data={value} />;
            })}
        </ul>
      </section>
      <section>
        contactos
        <input type='search' name='searchContact' id='searchContact' />
        <div>
          <ul>
            {contact.length > 0 &&
              contact.map((data, index) => {
                return <Contact key={index} data={data} />;
              })}
          </ul>
        </div>
      </section>
      <section>
        crear grupo y contacto
        <button onClick={handlerFormContact}>Añadir Contacto</button>
        {addContact && (
          <FormContact
            setAddContact={setAddContact}
            setContact={setContact}
            contact={contact}
          />
        )}
        <button onClick={handlerFormGroup}>Crear Grupo</button>
        {addGroup && (
          <FormGroup
            group={group}
            setGroup={setGroup}
            setAddGroup={setAddGroup}
          />
        )}
      </section>
    </div>
  );
}
